### ISSUE TITLE
What's the rationale for not supporting 200s on PUTs?

### ISSUE THREAD

**Issue by wryun** [eruvanos/openbrokerapi#1]
Seems easy to implement; would be useful for us.

**Comment by x6j8x** [comment]
As you‘ve already observed, that would break asynchronous operation. Or the api would have to become stateful (mapping operation data string to service id). Both options do not seem to be desirable.

**Comment by eruvanos** [comment]
I didn't found a good solution to differentiate between "200-OK" and "201-Accepted" as a return value from the functions.

In addition it seems not to be a common case that a cloud controller is putting with the same service instance twice.

PS. Sry for delay.

**Comment by wryun** [comment]
Because the 'Orphan Handling' section is a 'should', rather than a 'must', our marketplace currently retries after 500s and has a flow like (PUT, if 409, PATCH), which makes it simpler to code (and makes sure that, if someone has deleted the underlying resource or the marketplace is for some other reason out of sync, we can self-heal).

In terms of implementation, you're already testing 'is_async' on the returned object, no? Couldn't you instead have an enum which had the possible returns? (Accepted/Created/OK)

**Comment by eruvanos** [comment]
Included in release v0.5.0.

Thanks for feedback.
