### ISSUE TITLE
Ability to register different classes based on Service Id

### ISSUE THREAD

**Issue by wryun** [eruvanos/openbrokerapi#2]
It would be nice to be able to register different objects for different service ids and have the library choose the right one based on the request. The only problematic method for this approach AFAIK is last_operation, where service_id is not required...

**Comment by jtwaleson** [comment]
I think this is a good idea. The optional parameter is currently not passed through in the code: https://github.com/eruvanos/openbrokerapi/blob/cf6e15ff38c819d40541b65811c78bc95a2973d4/openbrokerapi/api.py#L248

I have submitted an issue at the Open Service Broker Specification project to make this a required field: https://github.com/openservicebrokerapi/servicebroker/issues/346

**Comment by eruvanos** [comment]
Will be build in with version 1.0.0
