### ISSUE TITLE
Remove python3.6 type annotations

### ISSUE THREAD

**Issue by jtwaleson** [eruvanos/openbrokerapi#3]
I would like to use this library for a service broker, but as type annotations are used, Python 3.6 is required. Overall, I think pushing for the latest and greatest is good, but for libraries compatibility is key.

Would it be OK to remove the variable type annotations of PEP 526 so this can be just Python 3.x compatible? If so, I'll submit a PR.

**Comment by eruvanos** [comment]
Sounds fine for me, that PR should also include doc strings so IDE's get still some hints about the returned type.

**Comment by eruvanos** [comment]
I already started to remove the type annotations. There are still some features left (like HTTPStatus) which was introduced with Python 3.5.

To support Python 3.x there are some tools supporting source code manipulation, like https://github.com/nvbn/py-backwards

Never used something like that.

I am open for discussion.
