### ISSUE TITLE
404 response to (un)binding call on unbindable service instance.

### ISSUE THREAD

**Issue by kazz-s** [eruvanos/openbrokerapi#41]
**Is your feature request related to a problem? Please describe.**
Binding call to an app with broker class that does not override un(bind) method will result with 500 reponse which is not pretty. OSB itself doesn't say how the broker should behave, however it says that broker may not implement binding endpoint so I'd interpreter this as not existing route.

**Describe the solution you'd like**
The "right" solution would be making registering un(bind) route conditional.
The simple solution would be catching NotImplementedError and produce 404 response.

**Comment by eruvanos** [comment]
That sounds great! I will work on that, or you can also create a pull request.

How you like.

**Comment by eruvanos** [comment]
Implemented responses with `501 NOT_IMPLEMENTED`, which seems to be the perfect fit.

Thanks
