### ISSUE TITLE
Create OSB API complience tests.

### ISSUE THREAD

**Issue by kazz-s** [eruvanos/openbrokerapi#42]
**Is your feature request related to a problem? Please describe.**
Official compliance tests are written in JavaScript and Python is superior :stuck_out_tongue: 

**Describe the solution you'd like**
adding additional module.

**Describe alternatives you've considered**
Create a separate project.

**Comment by eruvanos** [comment]
That sounds like a lot of work, but would be a good idea. Also using the JS compliance tests from https://github.com/openservicebrokerapi/osb-checker would be a nice thing in general.

**Comment by kazz-s** [comment]
Yea. I'm using that checker as well, but after few ours of reading JS code I need therapy. :P

**Comment by eruvanos** [comment]
Issue is cover in #15
