### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'is_async'

### ISSUE THREAD

**Issue by rlewkowicz** [eruvanos/openbrokerapi#57]
**Describe the bug**
```
broker_1  | Traceback (most recent call last):
broker_1  |   File "/root/.local/share/virtualenvs/broker-S8r40sTo/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
broker_1  |     rv = self.dispatch_request()
broker_1  |   File "/root/.local/share/virtualenvs/broker-S8r40sTo/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
broker_1  |     return self.view_functions[rule.endpoint](**req.view_args)
broker_1  |   File "/root/.local/share/virtualenvs/broker-S8r40sTo/lib/python3.7/site-packages/openbrokerapi/api.py", line 278, in deprovision
broker_1  |     add_service_id_to_async_response(result, broker.service_id())
broker_1  |   File "/root/.local/share/virtualenvs/broker-S8r40sTo/lib/python3.7/site-packages/openbrokerapi/api.py", line 90, in add_service_id_to_async_response
broker_1  |     if response.is_async:
broker_1  | AttributeError: 'NoneType' object has no attribute 'is_async'
broker_1  | 2019-05-03 16:07:48,039 - ERROR - broker.broker - 'NoneType' object has no attribute 'is_async'
```

In cloud foundry, I have a service broker which I've stood up. It has a functioning catalog endpoint and is registered with cloud foundry. 

When I goto create a service with it, it just dies. At a glance (I'm still digging) it's dying on deprovisioning. I don't have the deprovisioning endpoint populated, as I'm just trying to see what I'm even getting from cloud foundry during a provision (What does service_details even contain? Thats what I'm after) and how this library lines up with the spec.

I guess I have all the questions. So the spec says endpoint x must respond with y. Like if I wanted to just return 200 do I just return "200" from these methods? Your skeleton just has `pass`. Which might be killing me for some reason. In flask I just do the thing (which might be what I go do) whats the best way to gain visibility into the library (besides digging through source, which I'm working on)?

**To Reproduce**
Go grab the skeleton project:
https://github.com/eruvanos/openbrokerapi-skeleton/blob/master/broker/broker.py

def your catalog. In provision do something like print(service_details). Or how ever you debug this, I'm still trying to get off the starting block. 

Don't modify anything else, register the broker, then try to provision a service with it. 

**Expected behavior**
I'd like to just return a 200 and dump output to console so I can see what that object is. Ultimately I'd like the context object that I'm guessing service_details contains.

**Additional context**
N/A

**Comment by rlewkowicz** [comment]
So I've been making modifications to docker images, but not pulling on the remote host. I've been confusing myself a bit, but the end result is still the same. 

```
cf create-service bind-route small bob
Creating service instance bob in org rml4d7y / space rml4d7y as rml4d7y...
Service broker error: 'NoneType' object has no attribute 'is_async'
FAILED
```

 I've gone so far as to comment out all methods other then the provision method, but it seems to die in the same spot line 90 None type has no is_async

**Comment by rlewkowicz** [comment]
So I just went with flask. I think this feels cool, but I'm not really sure the value add.

**Comment by eruvanos** [comment]
I will have a look, thx for reporting
