### ISSUE TITLE
Improper Content-Type header. Expecting \"application/json\"

### ISSUE THREAD

**Issue by dcuenot** [eruvanos/openbrokerapi#67]
Hello,

**Describe the bug**
I'm trying to use the scaffolder to produce an OSB API. I manage to generate the /catalog.
However when I try to use the provisionning, I'm getting this output:
`{"description":"Improper Content-Type header. Expecting \"application/json\""}`

I'm a beginner in python, so maybe the answer will be very simple :(

FInd below how to reproduce:

**To Reproduce**
First API call to check that the catalog is working well:
```
(openbrokerapi-skeleton) ➜  runnerz git:(master) ✗ curl -s -H "Content-Type: application/json" -H "X-Broker-API-Version: 2.14" \
-X GET http://127.0.0.1:5000/v2/catalog | jq .
{
  "services": [
    {
      "bindable": false,
      "description": "Self registering",
      "id": "cicd-self-register",
      "name": "self-registering",
      "plan_updateable": false,
      "plans": [],
      "tags": [
        "self-service"
      ]
    }
  ]
}
```

Second call for the provisionning:
```
(openbrokerapi-skeleton) ➜  runnerz git:(master) ✗ curl -H "Content-Type: application/json" -H "X-Broker-API-Version: 2.14" \   
-X PUT http://127.0.0.1:5000/v2/service_instances/cicd-self-register
{"description":"Improper Content-Type header. Expecting \"application/json\""}
```

But the header is here (**-H "Content-Type: application/json"**)... So it's weird.
I'm using python 3.6.9 if it could help.

Below this is my code:

```
    def catalog(self) -> Service:
        return Service(
            id='cicd-self-register',
            name='self-registering',
            description='Self registering',
            bindable=False,
            plans=[],
            tags=['self-service'],
            plan_updateable=False,
        )

    def provision(self, instance_id: str, service_details: ProvisionDetails,
                  async_allowed: bool) -> ProvisionedServiceSpec:
        if instance_id == "cicd-self-register":
            return ProvisionedServiceSpec(
                ProvisionState.SUCCESSFUL_CREATED,
                "https://cicd.io"
            )

```

**Expected behavior**
I'm excepting a 200 return code

**Comment by eruvanos** [comment]
Hi, I will have a look, happy to see you here :)

**Comment by eruvanos** [comment]
So had a look:

The main problem is, that you are not sending any body, this is the reason, why the error says it is expecting a different type. (The error message is not precise about that.)

For more information about the requests you can check the [specification](https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md#provisioning).

```
curl -H "Content-Type: application/json" -H "X-Broker-API-Version: 2.14" -X PUT http://127.0.0.1:5000/v2/service_instances/cicd-self-register -d '{
  "service_id": "cicd-self-register",
  "plan_id": "cicd-self-register-standard",
  "organization_guid": "org-guid-here",
  "space_guid": "space-guid-here"
}
```

But to make this word, you have also to provide a service plan in your catalog:

```
    def catalog(self) -> Service:
        return Service(
            id='cicd-self-register',
            name='self-registering',
            description='Self registering',
            bindable=False,
            plans=[ServicePlan('cicd-self-register-standard', 'standard', 'Self registering ...')],
            tags=['self-service'],
            plan_updateable=False,
        )
```


If you want to test your broker, I recommend to write unit tests, calling the broker object directly without any HTTP layer. You can do some integration tests later with the connected platform.

Let me know, if you need any further help.

**Comment by dcuenot** [comment]
Ooooohhh my bad!

It's working with the right payload :)
Thanks for your help.

Other "silly" question, do you know if I can integrate your code in an Azure function?

**Comment by eruvanos** [comment]
This should be possible, there are wrapper for Flask and AWS Lambda, I guess also for Azure.
