### ISSUE TITLE
Question regarding multiple Services in a single service broker

### ISSUE THREAD

**Issue by tamirshaul** [eruvanos/openbrokerapi#72]
Hi,
I was wondering what is the correct way to provide a list of Services to the ```catalog``` method?
On the example I see that you can register only one:
```python
    def catalog(self):
        return Service(
            id='00000000-0000-0000-0000-000000000000',
            name='example-service',
            description='Example Service does nothing',
            bindable=True,
            plans=[
                ServicePlan(
                    id='00000000-0000-0000-0000-000000000000',
                    name='small',
                    description='example service plan',
                ),
            ],
            tags=['example', 'service'],
            plan_updateable=True,
        )
```
On my situations services are created and fetched dynamically from another API service.

Thanks for the help,
Tamir

**Comment by eruvanos** [comment]
When the broker starts, you can give multiple ServiceBrokers to be served.

Does that fit your needs?

```
# or with multiple service brokers and multiple credentials
api.serve([ExampleServiceBroker(), ExampleServiceBroker()], [api.BrokerCredentials("", ""), api.BrokerCredentials("", "")])
```

**Comment by tamirshaul** [comment]
Unfortunately no, I need to add services while the broker is running, is there another approach I can use?
Thanks!

**Comment by eruvanos** [comment]
Not yet, but I could integrate that again. It was a feature I dropped on the way to split up the implementation of different services.

**Comment by eruvanos** [comment]
I will have a look on the weekend, maybe it is easy to fix.

**Comment by tamirshaul** [comment]
Thanks so much! I appreciate it

**Comment by eruvanos** [comment]
Please give me a little bit more information about your whole setup, like the calling platform etc.

**Comment by tamirshaul** [comment]
Hey, sorry for the late answer,
We are currently working on Openshift and we have another automation platform which we populate automations (also new automations on a daily basis) with a survey of parameters for customers to use.
those automations can be ran through API .

We want to populate those automations as services to Openshift with a broker (the survey will be translated to plan parameters)

When the ```provision``` method is called from Openshift we will trigger the automation platform API to run the correct automation with the given params.

Thanks again,
Tamir

**Comment by eruvanos** [comment]
Thank you for those insights.
Right now I am thinking about refactoring. 
It makes sense to encapsulate the existing multibroker code into some kind of middleware. Which could be implemented differently for a dynamic reload.

Will start a branch and let you know about the progress.

**Comment by tamirshaul** [comment]
Thank you so much for your help, can't wait!

**Comment by eruvanos** [comment]
Some progress: https://github.com/eruvanos/openbrokerapi/blob/multibroker/doc/_static/single_broker.py

The multibroker branch has some progress, I will put in some more work to support the new API calls of the latest spec updates. Will release the new major version in a few days I guess.

**Comment by eruvanos** [comment]
Hi @tamirshaul and @wdesplas,
please have a look on the current master build
`pip3 install git+https://github.com/eruvanos/openbrokerapi.git`

Still have to heck if the changes cover all changes to API version 2.14, but it would be nice to know if you face any issues or anything does not work at all.

Thank you in advance.

**Comment by eruvanos** [comment]
Release is published.
Hope it works out for you now.
