### ISSUE TITLE
Able to manage more than one services in catalog

### ISSUE THREAD

**Issue by wdesplas** [eruvanos/openbrokerapi#81]
---
name: multi-service-catalog
about: Be able to manage more than one service in the catalog.

**Is your feature request related to a problem? Please describe.**
It's not possible for me to manage the the multi-service in catalog. As example, I return a dict as catalog and the solution must be able perform all the actions of the openbrokerapi spec.
Exampe of catalog that I return:
```
{
  "services": [
    {
      "id": "service id1",
      "name": "service name1",
      "description": "service description1",
      "bindable": false,
      "instances_retrievable": false,
      "bindings_retrievable": false,
      "plan_updateable": false,
      "plans": [
        {
          "id": "plan id1",
          "name": "plan name1",
          "description": "plan description1"
        }
      ]
    },
    {
      "id": "service id2",
      "name": "service name2",
      "description": "service description2",
      "bindable": false,
      "instances_retrievable": false,
      "bindings_retrievable": false,
      "plan_updateable": false,
      "plans": [
        {
          "id": "plan id1",
          "name": "plan name2",
          "description": "plan description2"
        }
      ]
    }
  ]
}
```

**Describe the solution you'd like**
Modify the Service class present in  service_broker.py (and the other scripts) to be able to manage the service object as a dict of services

**Additional context**
One way to bypass that is to pass the all the catalog without the class Service (dict) as follow:
```
    def catalog(self) -> Union[Service, List[Service]]:
        return self.dbmanager.get_catalogs()['services']
```

Then modify in the api.py script the _check_plan_id method as follow (can be more pretty to include both cases).  I substitude the class Service by using a dict that contains all needed informations to work with.

```
def _check_plan_id(broker: ServiceBroker, plan_id) -> bool:
    """
    Checks that the plan_id exists in the catalog
    :return: boolean
    """
    for service in ensure_list(broker.catalog()):
        #for plan in service.plans:
        for plan in service['plans']:
            #if plan.id == plan_id:
            if plan['id'] == plan_id:
                return True
    return False
```

**Comment by eruvanos** [comment]
Hi,
I am really happy, that you reach out.

Please take a look here: https://openbrokerapi.readthedocs.io/en/latest/overview.html#provide-one-or-more-services-with-one-broker

Let me know, if this fits your problem, or if there is something missing or unclear.

Happy to help you at any time :)

**Comment by wdesplas** [comment]
Thanks a lot for your answer. However, as my services catalog is dynamic and outside of the script, I can't instanciate a class like that( i don't even know the content of the catalog .I will override the method _check_plan_id to fit my need.

**Comment by eruvanos** [comment]
Ok,
thanks for the update.

Short question, did you considered to unpack your dicts?

```
def catalog(self) -> Union[Service, List[Service]]:
    return [Service(**params) for params in self.db.get_catalogs()['services']]
```

**Comment by wdesplas** [comment]
Hi,
Yes, I can as well create à list of services by unpacking the services catalogs and set Service(**params). I will do one the next release of my project. 

Moreover, If you need any help on the openbrokerapi do not hesitate to let me know.

Br,
Willy
