### ISSUE TITLE
Add LDAP authentication as authentication method

### ISSUE THREAD

**Issue by wdesplas** [eruvanos/openbrokerapi#83]
**Is your feature request related to a problem? Please describe.**
I have to implement a external authentication for my project and I would appreciate if this feature is present in the api.BrokerCredentials method.

**Describe the solution you'd like**
I will try to implement flask-wtf flask-sqlalchemy flask-login inside the broker in order to be able to use LDAP authentication by following [this](https://code.tutsplus.com/tutorials/flask-authentication-with-ldap--cms-23101) implementation.

**Additional context**
Could you please let me know if this feature seems fine for you and I will make a pull request accodingly.

Br,
Willy DESPLAS

**Comment by eruvanos** [comment]
Thank you for your input, I will have a look.

**Comment by eruvanos** [comment]
Hey,
I would like to understand the usecase, would the platform authenticate with a technical user from LDAP to call the provision, deprovision, etc. ?

Or are you using it for user authentication for a dashboard or something else?

**Comment by wdesplas** [comment]
Hi,

It will be in the case to be able to register your application into a marketplace (/v2/catalog). However, I will implement as well the authentication during all the other process (provisionng ...) by using the json parameters ([-c option](http://cli.cloudfoundry.org/en-US/cf/create-service.html) in cloudfoundry) as :
 ```
{
  "broker_user":"usermane",
  "broker_password":"p3ssword"
}
```

**Comment by eruvanos** [comment]
HI,
hope you were able to implement it, from my point of view, this is a very specific use case, that should be implemented outside.

Feel free to reopen this issue, if you want to discuss more.

Really appreciate your ticket, thank you.
